<div if="faq">
<h3>How can I place an order?</h3>
<p>Choose a product and click on the image to view the the item's details and purchase options. To proceed with the order, add the item to the cart and proceed to check out. If the order has been placed and sent correctly, you will receive a confirmation e-mail. If you do not receive it, check the e-mail address you entered during the purchase or look for the confirmation e-mail in the junk mail.
</p>
<h3>I received an error message while placing my order, what can I do?</h3>
<p>Our customer care is always at your disposal to help you with the purchase procedure. If you encounter a problem you can call us, chat with us, or send us a message by attaching a screenshot of the page where the error occurred. Alternatively you can write to customer.service@yamamay.com
</p>
<h3>How can I view the status of my order?</h3>
<p>You can view the information of your orders (in progress and past), by logging into your account, in the "My orders" section. If you have not registered on yamamay.com, you will find all the information in the order confirmation email.
</p>
<h3>Is there a limit to the amount of products I can purchase?</h3>
<p>There are generally no limits regarding quantity or amount. However, Yamamay may reserve the right to limit the purchase of some particular limited series products.
</p>
<h3>Can I change an order?</h3>
<p>You can change the order until the payment is confirmed. Once payment is received, it is no longer possible to change the order. This includes changing the size or color, removing or adding items, changing the billing address and the payment method.
</p>
<h3>What can I do if the item I want is not in stock?</h3>
<p>If the color or size of an item is out of stock, it will be marked as "Not available"; you can choose to be notified when it is back in stock by entering your email in the appropriate field and clicking on "Notify me".
</p>
<h3>Can I change an order?</h3>
<p>No. You can put all the items you want in the shopping bag and decide not to complete your order.
</p>  
</div>