<div class="container">
    <div class="space space--medium">
      <h2>Glide slider #1</h2>
      <p>Glide as type slider</p>
      <div id="glide-demo-slider1" class="slider glide glide--ltr glide--slider glide--swipeable">
        <div class="slider__track glide__track" data-glide-el="track">
          <ul class="slider__slides glide__slides"
            style="transition: transform 0ms cubic-bezier(0.165, 0.84, 0.44, 1) 0s; width: 2540px; transform: translate3d(255px, 0px, 0px);">
            <li class="slider__frame glide__slide glide__slide--active">0</li>
            <li class="slider__frame glide__slide">1</li>
            <li class="slider__frame glide__slide">2</li>
            <li class="slider__frame glide__slide">3</li>
            <li class="slider__frame glide__slide">4</li>
            <li class="slider__frame glide__slide">5</li>
            <li class="slider__frame glide__slide">6</li>
            <li class="slider__frame glide__slide">7</li>
            <li class="slider__frame glide__slide">8</li>
            <li class="slider__frame glide__slide">9</li>
          </ul>
        </div>

        <div data-glide-el="controls">
          <button class="slider__arrow slider__arrow--prev glide__arrow glide__arrow--prev" data-glide-dir="<">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
              <path d="M0 12l10.975 11 2.848-2.828-6.176-6.176H24v-3.992H7.646l6.176-6.176L10.975 1 0 12z"></path>
            </svg>
          </button>

          <button class="slider__arrow slider__arrow--next glide__arrow glide__arrow--next" data-glide-dir=">">
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24">
              <path d="M13.025 1l-2.847 2.828 6.176 6.176h-16.354v3.992h16.354l-6.176 6.176 2.847 2.828 10.975-11z">
              </path>
            </svg>
          </button>
        </div>

        <div class="slider__bullets glide__bullets" data-glide-el="controls[nav]">
          <button class="slider__bullet glide__bullet glide__bullet--active" data-glide-dir="=0"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=1"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=2"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=3"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=4"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=5"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=6"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=7"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=8"></button>
          <button class="slider__bullet glide__bullet" data-glide-dir="=9"></button>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
require(['jquery', 'glide', 'domReady!'], function($,  Glide){
    $(function(){
        var glide = new Glide('#glide-demo-slider1', {
            type: 'slider',
            focusAt: 'center',
            perView: 3
        })
        glide.mount()
    });
});
</script>
<!-- <div class="container">
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://picsum.photos/200" class="d-block w-100" alt="uno">
    </div>
    <div class="carousel-item">
      <img src="https://picsum.photos/200" class="d-block w-100" alt="due">
    </div>
    <div class="carousel-item">
      <img src="https://picsum.photos/200" class="d-block w-100" alt="tre">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div> -->
